title = "Daniel Melanson"
baseURL = 'https://melanson.dev/'
languageCode = 'en-us'
defaultContentLanguage = "en-us"
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"]

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
	[markup.tableOfContents]
		startLevel = 2 # ToC starts from H2
		endLevel = 4 # ToC ends at H4
		ordered = false # generates <ul> instead of <ol>

############################## English language ################################
[Languages.en-us]
  languageName = "English"
  languageCode = "en-us"

  [Languages.en-us.menu]
  [[Languages.en-us.menu.main]]
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[Languages.en-us.menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[Languages.en-us.menu.main]]
    pageRef="about"
    name = 'About'
    url = '/about/'
    weight = 30

[params.author]
  intro = "Awesome hugo blog"
  name = "Daniel Melanson"
  description = "Software engineer and programmer. Building web platforms for the U.S. Department of Homeland Security at MITRE."

# Allow to override webmanifest options
[params.webmanifest]
  name = "sitename" # will use "params.sitename" or "title" by default
  short_name = "sitename" # same as name
  start_url = "/" # will use homepage url by default
  theme_color = "#434648" # default is "#434648" (base color of text). Also will override html `<meta name="theme-color" />`
  background_color = "#fff" # by default depend on "params.defaultColor" for "light" or "auto" will be set to "#fff" for dark will be "#131418" (color of dark mode background)
  display = "standalone"

[[params.socialIcons]]
name = "github"
url = "https://github.com/daniel-melanson"

