title = "Daniel Melanson"
baseURL = 'https://melanson.dev/'
languageCode = 'en-us'
defaultContentLanguage = "en-us"
enableEmoji = true

[params]
[params.author]
name = "Daniel Melanson"
[[params.social]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/daniel-w-melanson/"
[[params.social]]
name = "LeetCode"
url = "https://leetcode.com/u/daniel-melanson/"
[[params.social]]
name = "Github"
url = "https://github.com/daniel-melanson"

[markup]
[markup.highlight]
style = 'onedark'

[module]
[[module.imports]]
path = 'github.com/hugomods/icons/vendors/font-awesome'
[[module.imports]]
path = 'github.com/hugomods/icons/vendors/lucide'
[[module.imports]]
path = 'github.com/hugomods/icons/vendors/simple-icons'
